name: rec_app
description: Medical transcription app for doctors
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  # Audio recording and processing
  record: ^6.1.1
  just_audio: ^0.9.36
  ffmpeg_kit_flutter_new_audio: ^1.1.0
  
  # Real-time audio streaming
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  
  # Native system integration
  flutter_local_notifications: ^17.2.1
  device_info_plus: ^9.1.0

  # Background services - Latest stable
  flutter_foreground_task: ^8.17.0

  # Permissions
  permission_handler: ^11.3.1


  # HTTP requests
  http: ^1.2.1
  dio: ^5.7.0

  # File operations
  path_provider: ^2.1.4

  # Network connectivity - Fixed version
  connectivity_plus:

  # State management
  provider: ^6.1.2

  # System integration
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2

  # UI components
  cupertino_icons: ^1.0.6
  
  # UUID generation
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true